chore: replace TravisCI with spec-prod
w3c/accname pull request #133
Opened 2021-06-18 08:54 UTC by marcoscaceres

@michael-n-cooper, I believe this should do the same thing as the .travis script. 

Question: any reason not to push to /TR/?

2021-06-18 10:11 UTC, michael-n-cooper commented
There are lots of reasons not to push to TR automatically. I'm on holiday so won't take time to elaborate them now. Please don't push any workflow changes to my repositories. I will look at the Travis -> GH actions change when I'm back, but don't plan in the short term to go further than pushing snapshots to gh-pages and would need lots of process coordination to go further.

2021-06-22 02:17 UTC, marcoscaceres commented
@michael-n-cooper, no problem - happy for you to handle it. When you are back, please see the email from @plehegar about our service with Travis ending. If you need a hand, just give me a shout! happy to help. 

Enjoy your break!!! 🏝

2021-06-24 15:23 UTC, plehegar requested changes

2021-06-24 15:23 UTC, plehegar commented on .github/workflows/auto-publish.yml
> +      - gh-pages
```suggestion
      - main
```

2021-06-24 15:23 UTC, plehegar commented on .github/workflows/auto-publish.yml
> +    name: Validate and Publish
```suggestion
    name: Validate and publish to gh-pages
```

2021-06-24 15:28 UTC, plehegar commented
Note: I didn't review the changes proposed to the JS code regarding respec. Apparently, the current code is broken and needs fixing. @marcoscaceres kindly introduced the fix in this pull request. This pull request could be split in two if it poses issues (ie one to switch to GitHub action and one to switch to fix the respec JS code).

2021-08-25 13:11 UTC, michael-n-cooper approved these changes

2021-08-25 13:13 UTC, merged