change computation ULs to OLs
w3c/accname pull request #188
Opened 2023-02-11 00:21 UTC by cookiecrook

resolves #185

pls merge #187 first, as this one branched from it

2023-02-11 00:24 UTC, cookiecrook commented
@spectranaut I noticed when starting this new PR that the template completely overwrites the multi-line commit message. It used to append the template to the commit message. What that a purposeful change? Since ~last week IIRC.

2023-02-11 00:25 UTC, cookiecrook commented on index.html
> +                        <li id="comp_labelledby_append" name="step2B.ii.c">Append a space character and the <code>result</code> to the <code>accumulated text</code>.</li>
Note that this is from #187, not #188.

2023-02-11 00:25 UTC, cookiecrook commented on index.html
> +            <li id="comp_append">Append a space character and the <code>result</code> of each step above to the <code>total accumulated text</code>.</li>
All remaining diffs are from #187, not #188.

2023-02-13 23:41 UTC, cookiecrook commented on index.html
> +            <li id="comp_append">Append a space character and the <code>result</code> of each step above to the <code>total accumulated text</code>.</li>
But those will disappear from this diff once PR #187 is merged.

2023-02-17 01:54 UTC, spectranaut commented
> @spectranaut I noticed when starting this new PR that the template completely overwrites the multi-line commit message. It used to append the template to the commit message. What that a purposeful change? Since ~last week IIRC.

I tried to see if you could preserve the commit messages while using a PR template, but there doesn't seem to be an option!

2023-02-17 01:59 UTC, spectranaut requested changes

2023-02-17 01:59 UTC, spectranaut commented on index.html
>                  <li id="comp_embedded_control_textbox"><em>Textbox:</em> If the embedded control has role <a class="role-reference" href="#textbox">textbox</a>, return its value.</li>
This list is an "unorder list", and looks odd, given everything else is ordered now

2023-02-17 03:28 UTC, spectranaut approved these changes

2023-02-27 21:04 UTC, MelSumner approved these changes

2023-02-28 23:44 UTC, cookiecrook commented
@jnurthen @spectranaut merge #187 then this one? thx

2023-03-01 19:01 UTC, merged