`name` not allowed on a `li` element
w3c/accname pull request #219
Opened 2023-11-03 23:29 UTC by jnurthen

Fixes #214

2023-11-03 23:50 UTC, cookiecrook requested changes
If you move the `id` to the `em`, you won't need the bogus `span`.

2023-11-03 23:51 UTC, jnurthen commented
> If you move the `id` to the `em`, you won't need the bogus `span`.

They don't all have an `em`

2023-11-03 23:55 UTC, cookiecrook commented
> > If you move the `id` to the `em`, you won't need the bogus `span`.
> 
> They don't all have an `em`

Okay keep the spans, but maybe add a comment? 

```html
<span id="step1"><!-- Don't link to this legacy numbered ID. --></span>
```

2023-11-04 01:20 UTC, cookiecrook approved these changes
Approve with contained diffs.

2023-11-04 01:20 UTC, cookiecrook commented on index.html
> +                <li id="comp_labelledby_foreach"><span id="step2B.ii"><!-- Don't link to this legacy numbered ID. --></span> each IDREF:
Looks like a few words got trampled.

```suggestion
                <li id="comp_labelledby_reset"><span id="step2B.i"><!-- Don't link to this legacy numbered ID. --></span> Set the <code>accumulated text</code> to the empty string.</li>
                <li id="comp_labelledby_foreach"><span id="step2B.ii"><!-- Don't link to this legacy numbered ID. --></span>For each IDREF:
```

2023-11-04 01:20 UTC, cookiecrook commented on index.html
> +                    <li id="comp_labelledby_set_current"><span id="step2B.ii.a"><!-- Don't link to this legacy numbered ID. --></span> the <code>current node</code> to the node referenced by the IDRE
```suggestion
                    <li id="comp_labelledby_set_current"><span id="step2B.ii.a"><!-- Don't link to this legacy numbered ID. --></span>Set the <code>current node</code> to the node referenced by the IDREF.</li>
```

2023-11-04 01:20 UTC, cookiecrook commented on index.html
> +                    <li id="comp_labelledby_append"><span id="step2B.ii.c"><!-- Don't link to this legacy numbered ID. --></span> a space character and the <code>result</code> to the <code>accumulate
```suggestion
                    <li id="comp_labelledby_append"><span id="step2B.ii.c"><!-- Don't link to this legacy numbered ID. --></span>Append a space character and the <code>result</code> to the <code>accumulated text</code>.</li>
```

2023-11-04 02:15 UTC, accdc commented
Is this editorial?

2023-11-04 03:34 UTC, jnurthen commented
> Is this editorial?

yes

2023-11-04 04:31 UTC, cookiecrook approved these changes

2023-11-04 21:32 UTC, merged